spring:
  datasource:
    password: 123456
    username: marcio
    url: jdbc:mysql://localhost:3306/fornecedor?useSSL=false&useTimezone=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
